// @ts-check
import { reactConfig } from './react.js';
import nextPlugin from '@next/eslint-plugin-next';

/** @type {import('eslint').Linter.Config[]} */
export const nextjsConfig = [
  ...reactConfig,
  {
    // Phase 12.4 — Next-app-specific ignores. `next lint` used to
    // scope the lint root to `app/` + `lib/`; the migration to
    // `eslint .` widens the scope to the whole app, so we have to
    // explicitly skip what Next generates / what Serwist emits into
    // public/.
    ignores: [
      // Auto-generated by `next dev` / `next build`. Triggers
      // @typescript-eslint/triple-slash-reference, which we keep on
      // for human-authored .d.ts files.
      '**/next-env.d.ts',
      // Static + Serwist-compiled service workers + assets. Not TS,
      // not in any tsconfig project — typed-aware lint can't reach
      // them and they aren't ours to format.
      '**/public/**',
    ],
  },
  {
    files: ['**/*.{ts,tsx,js,jsx}'],
    plugins: {
      '@next/next': nextPlugin,
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
    },
  },
  {
    files: ['app/**/{page,layout,loading,error,not-found,template,default}.{ts,tsx}'],
    rules: {
      'import/no-default-export': 'off',
    },
  },
  {
    // Files Next.js looks for by convention — they each expect a
    // default export of a config / hook / instrumentation function.
    // The base config bans default exports; carve these out.
    files: [
      'next.config.{js,mjs,ts}',
      'middleware.{js,ts}',
      'i18n.{js,ts}',
      'instrumentation.{js,ts}',
      'instrumentation-client.{js,ts}',
    ],
    rules: {
      'import/no-default-export': 'off',
    },
  },
];
